patch ../aria2/src/OptionHandlerFactory.cc ./patch/1.patch
patch ../aria2/src/DownloadCommand.cc ./patch/2.patch
patch ../aria2/src/SocketBuffer.cc ./patch/2.patch
patch ../aria2/src/SocketCore.cc ./patch/2.patch
patch ../aria2/src/HttpSkipResponseCommand.cc ./patch/3.patch
patch ../aria2/src/OptionHandlerFactory.cc ./patch/3.patch
patch ../aria2/src/prefs.cc ./patch/3.patch
patch ../aria2/src/prefs.h ./patch/3.patch
patch ../aria2/src/usage_text.h ./patch/3.patch
patch ../aria2/src/AbstractProxyRequestCommand.cc ./patch/4.patch
patch ../aria2/src/HttpRequestCommand.cc ./patch/4.patch
patch ../aria2/src/OptionHandlerFactory.cc ./patch/4.patch
patch ../aria2/src/prefs.cc ./patch/4.patch
patch ../aria2/src/prefs.h ./patch/4.patch
patch ../aria2/src/usage_text.h ./patch/4.patch
